version: 0.0
os: linux
files:
  - source: /      
    destination: /home/ubuntu/code_rivio
    overwrite: true             
file_exists_behavior: OVERWRITE  

hooks:
  AfterInstall:
    - location: scripts/install.sh 
      timeout: 300
